### ISSUE TITLE
Outdated LibreOffice integration submodule

### ISSUE THREAD

**Issue by agkphysics** [zotero/zotero-standalone-build#102]
I believe commit e40273b282e1a904a4f51c1a7d2cfbd2a125160a made the LibreOffice submodule revert back to [a commit](https://github.com/zotero/zotero-libreoffice-integration/commits/5c6fbec74dfcb94a4b025938520e5e8430d800db) from 2016, and I assume this was accidental?

It has caused an issue for the Arch Linux source package [here](https://aur.archlinux.org/packages/zotero#comment-879359) since this build repo is cloned from the latest commit as per the instructions.

**Comment by adomasven** [comment]
Fixed in https://github.com/zotero/zotero-standalone-build/commit/8a67365e229a5e0fa5a6359305b1ddca58eafa67

Yeah, that was a mistake, sorry for causing any trouble.

**Comment by dstillman** [comment]
@agkphysics: Just to note, while this was certainly a mistake, there's never a guarantee that the current zotero-standalone-build commit is safe to use, so you shouldn't package it blindly from that. We generally add a tag to zotero-standalone-build whenever a Zotero version is being pushed out that includes new zotero-standalone-build commits. We hadn't done that for the last few releases — sorry! — but I've added the tag now. (As you can see, the latest is 6.0.10, meaning 6.0.10 through 6.0.13 have been based on that commit.)

**Comment by agkphysics** [comment]
@dstillman Okay thanks. I'll make it checkout the latest stable tag of this repo, as it already does for the main Zotero repo.
