### ISSUE TITLE
Packaging for Alpine Linux

### ISSUE THREAD

**Issue by ayakael** [zotero/zotero-standalone-build#114]
I am packaging Zotero for Alpine Linux [here](https://lab.ilot.io/ayakael/user-aports/-/merge_requests/86). As no binaries are built for musl-based systems, I have no choice but to build from source.

While I've managed to get zotero built, I've hit a stumbling block with Firefox binaries not being available for linux-musl. It is my understanding that y'all modify the binaries for your usage. Is there a way to build Firefox from source especially for Zotero (i.e. with only the components - like xulrunner - that are used)?

We have a Firefox package, but I'm not sure how to feed that into the Zotero build process. Since y'all also need a very specific version of Firefox, I'd also prefer building it within the Zotero build process.

**Comment by dstillman** [comment]
On macOS and Windows we need custom versions of the Firefox app launcher, but on Linux we just use a [shell script](https://github.com/zotero/zotero-standalone-build/blob/master/linux/zotero) (and old Firefox updater binaries, but you wouldn't need those).

We do make modifications to the Firefox package, though — see [fetch_xulrunner.sh](https://github.com/zotero/zotero-standalone-build/blob/master/fetch_xulrunner.sh) for the script. If you point that at an equivalent Firefox tarball for your distro, it might work, assuming the tarball tracks the official one.

**Comment by ayakael** [comment]
So I've managed to get Zotero working. The problem is that maintaining a full Firefox build is hard - building Firefox is a process the tends to break down easily. Is there specifically a component of Firefox that zotero needs to function? The idea being to be able to build a stripped down version of Firefox for exclusive usage by Zotero.

In general, it'd be nice if a buiild-from-source guide can be produced, as I'm sure that facilitating inclusion of zotero in linux repo's would be benificial for the project.

**Comment by ayakael** [comment]
Closing as implemented aport package for Alpine Linux here: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/60178

It builds Firefox 102 from source and feeds it into Zotero's build process.
