### ISSUE TITLE
pdfinfo pdftotext Debian

### ISSUE THREAD

**Issue by heiserhorn** [zotero/zotero-standalone-build#28]
Hi,

I am maintaining zotero-standalone in Debian and have this bug reported (Bug#708508).

In the configuration dialog

(Edit→Options...→Search)

cannot find pdfinfo-Linux-x86_64 and
pdftotext-Linux-x86_64.

/usr/bin/pdfinfo and /usr/bin/pdftotext are in the package
poppler-utils.

When poppler-utils is installed zotero serhes for the -Linux-x86_64
suffix in their names.

Zotero should first search for /usr/bin/pdfinfo and .../pdftotetext and if
that failed for where/ever/pdfinfo-Linux-x86_64
and .../pdftotext-Linux-x86_64.

Cheers

Mike

**Comment by JackieMium** [comment]
I downloaded
```
pdfinfo: https://www.zotero.org/download/xpdf/pdfinfo-Linux-x86_64-3.02
pdftotext: https://www.zotero.org/download/xpdf/pdftotext-Linux-x86_64-3.02
```
and now what? I am using Debian Sid and I moved `pdfinfo` & `pdftotext` -Linux-x86_64 to `/bin` and Zotero still complains. I renamed `pdfinfo` & `pdftotext` -Linux-x86_64  to `pdfinfo` and `pdftotext` and problem presists.
