### ISSUE TITLE
Preference window empty

### ISSUE THREAD

**Issue by heiserhorn** [zotero/zotero-standalone-build#35]
In Debian the preference window is empty wit Gecko version 31 or 32 but the with the extension works fine. See bug for more details https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757610

Cheers

Mike

**Comment by simonster** [comment]
This was probably fixed as part of a281e17d176cbe1fcfa4d627984bf8dd8c81a9da. I encountered the same issue when repackaging Firefox as the XUL host and traced it to `browser.preferences.instantApply`.
