### ISSUE TITLE
Zotero to Bibtex command line

### ISSUE THREAD

**Issue by bsaleil** [zotero/zotero-standalone-build#37]
Hi.

The only reason why I'm not using Zotero at the moment is that I can't integrate it with my latex build process (using make).
I think an important feature is the ability to use the translators from the standalone command line.
(In my case: zotero->bibtex)

**Comment by aurimasv** [comment]
Please post feature suggestions to the forums. This issue tracker is for developer use only (and is in no way related to your question anyway)
