### ISSUE TITLE
Wrong icon path on Ubuntu 15.04

### ISSUE THREAD

**Issue by joelostblom** [zotero/zotero-standalone-build#38]
By default, Zotero standalone uses the [dictionary icon](https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiCr7nc0qTJAhWEez4KHTnrAQ8QjRwIBw&url=http%3A%2F%2Fwww.1001freedownloads.com%2Ffree-icon%2Fapps-dictionary-icon&psig=AFQjCNEGa-VzBVI46PPd-oN7JM8YeWO4uw&ust=1448302857242394) on Ubuntu 15.04.

Changing the icon path in `/usr/share/applications/zotero.desktop` from:

```
[Desktop Entry]
Name=Zotero
Comment=Open-source reference manager (standalone version)
Exec=/opt/zotero/zotero
Icon=accessories-dictionary
Type=Application
StartupNotify=true
```

to

```
[Desktop Entry]
Name=Zotero
Comment=Open-source reference manager (standalone version)
Exec=/opt/zotero/zotero
Icon=/opt/zotero/chrome/icons/default/default48.png
Type=Application
StartupNotify=true
```

fixes the problem.

**Comment by epiraces** [comment]
The same applies to 16.04, by the way.

**Comment by dstillman** [comment]
We don't distribute an Ubuntu package, so you'll have to report this to the maintainer of that package.
