### ISSUE TITLE
zotero standalone script in Linux not passing the "--url" parameter

### ISSUE THREAD

**Issue by rdiaz02** [zotero/zotero-standalone-build#39]
The Zotero standalone script in Linux ignores aditional arguments and, in particular, does not pass the "--url" parameter. Therefore, it is impossible to get calls such as `run-zotero.sh --url zotero://select/items/itemid` to work directly.

The identificaton of the problem and the possible workarounds have been provided by @willsALMANJ in this [Zutilo issue](https://github.com/willsALMANJ/Zutilo/issues/47#issuecomment-165952292). Here I report the script issue.

The Mozilla script (called `run-zotero.sh` if one uses the Zotero standalon tar.bz2 available from the [download page](https://www.zotero.org/download/), or `zotero`, under `/usr/bin` in at least some distributions) does not pass its argument in the expected way. 

Looking at that script, it looks like it is supposed to pass all of its arguments on to the main Zotero binary here: <https://github.com/zotero/zotero-standalone-build/blob/master/linux/run-zotero.sh#L398> but it is processing the first argument to use as the program to call here: <https://github.com/zotero/zotero-standalone-build/blob/master/linux/run-zotero.sh#L239>. Passing the binary (which can be under, e.g.,  `Zotero_linux-x86_64` or under `/usr/lib/zotero`) as the first argument in a call like `run-zotero.sh /path/to/zotero/binary/zotero --url zotero://select/...` works for me the same as calling    `/path/to/zotero/binary/zotero --url zotero://select/..`  directly.

**Comment by dstillman** [comment]
Despite its name, `run-zotero.sh` isn't actually what you should be using for starting Zotero. (It's a repackaged Mozilla script, and I'm actually not sure why we bundle it — @simonster would be able to say more.) But just use the main binary, `zotero`, and command-line flags (e.g., `-jsconsole`) will work. (`zotero://select` not working at startup is a [separate matter](https://github.com/zotero/zotero-standalone-build/issues/40), as you note.)

**Comment by rdiaz02** [comment]
Aha, understood. May I suggest that the help, under "Zotero options", also show explicitly "--url" as a command line flag? The "Usage" section might give the impression that a URL passed at the end will  be taken as such, but it does not unless one uses "--url", which is not clear (to me at least) unless I look at the code.

**Comment by juanmah** [comment]
Running `/usr/lib/zotero/zotero` works, but linking `/usr/bin/zotero` to `/usr/lib/zotero/zotero` and running `/usr/bin/zotero` doesn't. It gives `Could not read application.ini` error.

Intead, linking `/usr/bin/zotero` to `/usr/lib/zotero/run-zotero.sh` and running `/usr/bin/zotero` works.

`run-zotero.sh` seems to have a function.

**Comment by dstillman** [comment]
That still doesn't mean that `run-zotero.sh` is the thing to run, though — just that the main binary determines the path to application.ini based on its own location and therefore doesn't work symlinked. We don't create the Linux packages, so run scripts aren't really our domain, but it'd be trivial for a package to create a run script that passes on command-line arguments if necessary:

```
#!/bin/sh
INSTALL_PATH=/usr/bin/zotero

cd $INSTALL_PATH
./zotero $*
```
