### ISSUE TITLE
zotero binary not handling zotero://select link passed on start up

### ISSUE THREAD

**Issue by rdiaz02** [zotero/zotero-standalone-build#40]
The identificaton of the problem has been provided by @willsALMANJ in this [Zutilo issue](https://github.com/willsALMANJ/Zutilo/issues/47#issuecomment-165952292). Here I report the problem with the binary at start up.

The zotero binary, called `zotero` (which can be under, e.g.,  `/some_dir/Zotero_linux-x86_64` if one downloads zotero from the [download page](https://www.zotero.org/download/) or under `/usr/lib/zotero` in some Linux distributions) will ignore the `--url` command line option if Zotero standalone is not running. (If it is already running, however, calling the binary with `zotero zotero://select/items/itemID` will do the right thing ---go to that reference). The relevant part of the code might be around here: https://github.com/zotero/zotero/blob/4.0/components/zotero-service.js#L406

**Comment by dstillman** [comment]
We probably won't fix this until 5.0, when it will be easier to have `zotero://select` automatically wait until the items list has finished loading.

**Comment by dstillman** [comment]
Should be fixed in the latest 5.0 (either release or <a href="https://www.zotero.org/support/dev_builds">beta</a>)
