### ISSUE TITLE
zotero --help should explicitly mention "--url"

### ISSUE THREAD

**Issue by rdiaz02** [zotero/zotero-standalone-build#41]
Right now, `zotero --help` (at least under linux systems) does not show  `--url` as a command line flag and the "Usage" section might give the impression that a URL passed at the end will  be taken as such, which it won't unless preceeded by `--url`. The only way to find out how to pass the url seems to be looking at the code (thus making it hard to realize how trivial it is to use `zotero://select`).

**Comment by twi001** [comment]
I find the option `--url zotero://select/... ` extremely helpful for Zotero integration in note taking systems such as the zettelkasten concept allowing direct links into Zotero. Before, I had tried `zotero URL` as described in the `zotero --help`, but gave up after some time since it didn't work. Just by chance I found a post discussing the `--url` option and the format for `zotero://select/...`. An update of the cli help would be very helpful!

**Comment by dstillman** [comment]
`--help` isn't something that comes from us — that's just from the Firefox binary that Zotero uses. If we change how Zotero is built, we might be able to customize that, but for now I'm closing this as WONTFIX.

But you don't need to use `--url` to use `zotero://select` — you just need to associate Zotero with `zotero://` URLs on your system. That happens automatically on macOS and Windows, but how you do that on Linux depends on your distro. It looks like the [zotero-deb](https://github.com/retorquere/zotero-deb) packages use a [desktop file](https://github.com/retorquere/zotero-deb/blob/master/official/zotero.desktop) that registers itself for the `zotero` scheme. Assuming that works, we'll look into adding that to the zotero.desktop file in the official tarball.

**Comment by rdiaz02** [comment]
Thanks for the details. 

In case it helps other Linux users: Indeed what I have been doing for several years now (I use Debian) is to create a desktop file, `zotero.desktop`, which lives under `$HOME/.local/share/applications`. In the `mimeapps.list` file (under `$HOME/.local/share/applications`) I have this line `x-scheme-handler/zotero=zotero.desktop`.

My `zotero.desktop` is a link to a script I wrote for my specific way of working that will either call the zotero binary when one passes something like `zotero://select/items` (I still use `--url`) or my chosen PDF viewer (Emacs in my case) when called as `zotero://open-pdf/`.

So, when I call from the shell (or any other application that uses xdg) something like `xdg-open zotero://select/items/whatever` zotero will open that entry, and when I do `xdg-open zotero://open-pdf/0_whatever/pagenumber` the whatever PDF is opened at that pagenumber.
