### ISSUE TITLE
Zotero not working with Word 2013 installed on Ubuntu 16.04 with Crossover 16

### ISSUE THREAD

**Issue by fsdias** [zotero/zotero-standalone-build#51]
I have Word 2013 working on Linux Ubuntu 16.04 installed with Crossover 16. I also have zotero standlone for windows installed with Crossover 16 in the same bottle. I installed zotero plugin with no issues, but when when I click on "add citation" this error message appears.

Zotero experienced an error updating your document.

An unhandled exception occured. [getDocument:document.cpp]'An unhandled exception occured. [getDocument:document.cpp]' when calling method: [zoteroIntegrationApplication::getDocument]

**Comment by dstillman** [comment]
This tracker is for developer use only (and wouldn't be the right one anyway). Please post support requests to the [Zotero Forums](https://forums.zotero.org/).
