### ISSUE TITLE
Provide a way to get to the latest installer

### ISSUE THREAD

**Issue by bochoven** [zotero/zotero-standalone-build#56]
Not sure if this is the right place to ask, but it would be great if you could provide a way for an automated system like AutoPKG to retrieve the latest installer for Zotero.

AutoPKG is an automated system based on recipes that retrieve software installers and processes them for install. The current recipe scrapes the Zotero download page and tries to construct the proper path to the download. This is of course not a very reliable system. Now that the download is generated by React, the html scraping is getting even more brittle.

If you could provide an xml feed of some sorts, or add the binaries to the GitHub release, that would tremendously help the Mac Admin community in providing the latest Zotero application to its users.

More information on AutoPKG: https://github.com/autopkg/autopkg
Link to the Zotero recipe: https://github.com/autopkg/joshua-d-miller-recipes/tree/master/Zotero

**Comment by dstillman** [comment]
```
curl --silent https://www.zotero.org/download/client/manifests/release/updates-mac.json | jq -r .[-1].version
```

**Comment by bochoven** [comment]
@dstillman Thanks for your response, but how would that json lead to the installer download?

```json
[
  {
    "major": false,
    "buildID": "20170709234418",
    "detailsURL": "https://www.zotero.org/support/5.0_changelog",
    "version": "5.0"
  },
  {
    "major": false,
    "buildID": "20170711102730",
    "detailsURL": "https://www.zotero.org/support/5.0_changelog",
    "version": "5.0.1"
  },
  {
    "major": false,
    "buildID": "20170712043426",
    "detailsURL": "https://www.zotero.org/support/5.0_changelog",
    "version": "5.0.2"
  },
  {
    "major": false,
    "buildID": "20170713040005",
    "detailsURL": "https://www.zotero.org/support/5.0_changelog",
    "version": "5.0.3"
  }
]```

**Comment by dstillman** [comment]
That will tell you the current version. If you're just looking for the download URL, it's just what's on the download page:

https://www.zotero.org/download/client/dl?channel=release&platform=mac&version=5.0.3

You can omit `version` to get the current version.

**Comment by bochoven** [comment]
Excellent! Thank you
