### ISSUE TITLE
Arch package

### ISSUE THREAD

**Issue by JonathanReeve** [zotero/zotero-standalone-build#57]
An Arch package would be very useful to users of Arch, Antergos, Manjaro, and other Arch-based distributions. (These are very high-ranked distros on distrowatch.com now.) There's already an Arch User Repository package for zotero, so making an official Arch package shouldn't be hard. Here are the [rules for entering a package](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines#Rules_for_Packages_Entering_the_.5Bcommunity.5D_Repo), which apparently only requires 10 votes (zotero has ~150). The only thing I would change is the auto-update preference--if zotero is installed system-wide, then it shouldn't auto-update.

**Comment by dstillman** [comment]
Sorry, this isn't something we plan to provide.
