### ISSUE TITLE
libreoffice integration: add-cite-dialog

### ISSUE THREAD

**Issue by n33l33m3lj** [zotero/zotero-standalone-build#61]
the add cite dialog closes immediately after I open it.

platform: debian stretch (9.2)
desktop environment: XFCE4.12
this happens with both zotero versions I tried (4.0.29.16 and 5.0.24), and with both extension versions.

when I open via terminal and click the button in libre office:

> Possibly unhandled rejection:
> 
> err is null
> 
> TypeError: err is null
>     logError@chrome://zotero/content/xpcom/zotero.js:1291:3
>     execCommand/<@chrome://zotero/content/xpcom/integration.js:313:7
> From previous event:
>     execCommand@chrome://zotero/content/xpcom/integration.js:271:11
>     Comm</DataListener.prototype._transactionCallbacks[0]<@file:///home/ao/Desktop/Zotero_linux-x86_64/extensions/zoteroOpenOfficeIntegration@zotero.org/components/zoteroOpenOfficeIntegration.js:168:6
>     Comm</DataListener.prototype._processFrame/<@file:///home/ao/Desktop/Zotero_linux-x86_64/extensions/zoteroOpenOfficeIntegration@zotero.org/components/zoteroOpenOfficeIntegration.js:273:7
>     this.setTimeout/timerCallback.notify@chrome://zotero/content/xpcom/zotero.js:1764:5
> 
>

**Comment by adomasven** [comment]
There's an error in your document that Zotero is not handling correctly. Either way, the tracker is for development use only, please post on [Zotero Forums](https://forums.zotero.org/). Providing a [Debug ID](https://www.zotero.org/support/debug_output) with your post might help.
