### ISSUE TITLE
Include category in the desktop file

### ISSUE THREAD

**Issue by nedrichards** [zotero/zotero-standalone-build#63]
the [.desktop file for Linux](https://github.com/zotero/zotero-standalone-build/blob/master/linux/zotero.desktop) doesn't specify any categories - which means that Zotero won't show up by default in a number of Linux software stores such as GNOME Software. A quick:

> Categories=Education;

Would probably be fine, but you may have different views on the [correct value](https://standards.freedesktop.org/menu-spec/latest/apa.html).

**Comment by arteymix** [comment]
It fits more into the Office category considering that the main purpose is to collect, manage and cite documents. It's not exclusive to scientific research.

**Comment by nedrichards** [comment]
Fair enough, I've pushed an update to the PR which says "Office" rather than "Education".
