### ISSUE TITLE
Building Zotero : fetch_pdftools error

### ISSUE THREAD

**Issue by gracile-fr** [zotero/zotero-standalone-build#67]
@mrtcode :
Following instructions <a href="https://www.zotero.org/support/dev/client_coding/building_the_standalone_client">there</a> on Windows 7 64-bit, I get:<blockquote>./fetch_pdftools: line 24: cd: too many arguments
</blockquote>

FWIW, the working directory is "C:\Dev Zotero\Git\build\zotero-standalone-build" (yes, there's a space). Could you help me?

**Comment by dstillman** [comment]
Fixed in fc3772e79834f653a2a522872336222f2c09fa10, probably — let us know if not.
