### ISSUE TITLE
To choose the program for openning a jpg file

### ISSUE THREAD

**Issue by livier** [zotero/zotero-standalone-build#70]
unusualy, I wanted to join a jpg file to a zotero document.
After I check if the file open well. Yes, it is well register, 
but it does not open with my usual light Gwenview, but with Krita witch is heavyer.
You understood I am on Linux,  Ubuntu Kde Neon (a jour).
- Why not opening whith the ordinary default one on the computer ?
- Can I choose, and how ?

Thanks for zotero

**Comment by dstillman** [comment]
Please post all support questions to the [Zotero Forums](https://forums.zotero.org/).

Zotero doesn't handle file associations themselves — it simply passes the file off to your OS.

https://www.zotero.org/support/kb/file_handling_issues
