### ISSUE TITLE
Dark theme issue on Linux

### ISSUE THREAD

**Issue by specter119** [zotero/zotero-standalone-build#72]
I am using the latest Zotero on Arch with KDE Plusma, and set GTK theme to Breeze-Dark.
Everything displays properly except the 'About' window and the Tag frame, both of them show a white background.
Besides, the font color of item type should be white instead of black.
Thanks for your cooperation.

**Comment by dstillman** [comment]
I'm not sure what you mean here — Zotero doesn't have a dark theme currently, and it's not something we support, so anything you're seeing isn't something we've done. We hope to support a dark mode in a future version.

(Also, please post all support requests to the [Zotero Forums](https://forums.zotero.org), not these trackers.)

**Comment by Goblin80** [comment]
KDE is trying to enforce system-wide theme on all applications (including zotero).

I suggest sticking with the light theme for Zotero by setting environment variable `GTK_Theme=Default`:

```bash
GTK_THEME=Default zotero
```
