### ISSUE TITLE
Fetching XUL runner gets stuck when modifying omni

### ISSUE THREAD

**Issue by m-mauersberger** [zotero/zotero-standalone-build#80]
Problem is on Zotero commit 49d9f587e2e740f7e387858676f585719866a615 (latest: 2020/07/02)
using openSUSE Leap 15.1
with Perl 5.26

When I run `fetch_xulrunner.sh -p l` following error occurs:
```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/get _inPrivateBrowsing\(\) { <-- HERE / at -e line 1.
```

It seems that the error lies within the program. Since Perl version 5.26 there is no more just warning if braces are unescaped in regular expressions ([source](https://github.com/domino-team/openwrt-cc/issues/24)). So maybe escaping will help...

[log_xul.txt](https://github.com/zotero/zotero-standalone-build/files/4864072/log_xul.txt)

**Comment by dstillman** [comment]
FWIW, it's working for me on Ubuntu 20.04 with Perl 5.30.
