### ISSUE TITLE
Register for zotero:// and MIME types on Linux

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-standalone-build#81]
@retorquere, have you found that the `MimeType` line in [your version of the desktop file](https://github.com/retorquere/zotero-deb/blob/master/official/zotero.desktop) actually does anything? I'm trying a desktop file with that in it, but I'm having trouble finding a context where it makes a difference.

Related: https://github.com/zotero/zotero-standalone-build/issues/41#issuecomment-668667696

**Comment by retorquere** [comment]
It does (just tried again on a clean install of Ubuntu 20.04). It looks like the apt tools invoke `xdg-mime default` in some way.

**Comment by dstillman** [comment]
Oh, so is it only on an apt install? The presence of the zotero.desktop file with that line in ~/.local/share/applications won't do it?

I'm basically asking if there's any reason to add this line to the stock desktop file in the tarball.

**Comment by retorquere** [comment]
Turns out no; as long as the desktop file is in either `/usr/share/applications` or `~/.local/share/applications`, xdg will find it. My debs were just putting them in `/usr/shar/applications`. Zotero has an install script that patches the desktop file, right? Might want to `ln` it to `~/.local/share/applications`; `ln` will work (just tested).

**Comment by dstillman** [comment]
I'm saying that I added your MimeType line to the official zotero.desktop, did a normal `ln -s` into `~/.local/share/applications` as per our official instructions, and I couldn't find a context where that did anything.

What are you suggesting I do differently? How are you testing whether it works?

**Comment by dstillman** [comment]
`xdg-mime query default x-scheme-handler/zotero` shows `zotero.desktop` for me, but a zotero://select link in Firefox (at least from a file:// URL) doesn't work, nor is Zotero offered when I go to Open With Other Application for a RIS file. So in what way is this doing something for you?

**Comment by retorquere** [comment]
I've been testing on a clean VM but apparently kept state between two tests. You're right -- after putting the desktop file in `~/.local/share/applications` you still need to run `xdg-mime default zotero.desktop x-scheme-handler/zotero` for urls to work in FF. And it does look like the apt installation process does that for the mimetypes listed in the desktop file automatically.

**Comment by retorquere** [comment]
Except for file extensions it still does not work; looks like `ris` eg is not known by default.

**Comment by inukshuk** [comment]
In my experience, you need to run `update-desktop-database` after installing a new desktop file. This updates the cache database containing the list of MIME types handled by desktop files. If you use `desktop-file-install` to install the file you can also use the `--rebuild-mime-info-cache` option, but you may have to run `update-desktop-database` regardless.

I would assume that running `xdg-mime default` is something a user would do if there were multiple different applications handling the same type and that it should not be necessary if Zotero is the only application registered for the URL scheme.

To register unknown MIME types you can use `xdg-mime install` with a short XML file describing the type. Or copy the files yourself, e.g., to `~/.local/share/mime` and `update-mime-database` afterwards. I think if your desktop file references the new MIME types you need to do this before `update-desktop-database`.

**Comment by retorquere** [comment]
Yeah looks like it, means I have to re-add the `postinst` script.

**Comment by karlicoss** [comment]
Hi, anyone knows if this functionality is working? Also is there any doc on how it was meant to work -- couldn't find anything, except some references to `zotero://` in the source code.

`./zotero-bin --help` doesn't show `-url` flag. Also, not sure if it was meant to be `--url`? https://github.com/zotero/zotero-standalone-build/blob/9d00c5cbdbb8628c51ca738fb14ba9a1f98bd98a/linux/zotero.desktop#L3
Either way, it doesn't really work -- grepped in the code for some examples of `zotero://` URLS, like `zotero://debug`, but when I run `./zotero-bin --url zotero://debug`, nothing happens? Or am I doing something wrong?

I'm using Zotero Beta, in case it matters.

**Comment by retorquere** [comment]
https://github.com/zotero/zotero-standalone-build/issues/81#issuecomment-668829050 and following comments explain what needs to be done.

**Comment by qubidt** [comment]
@karlicoss [this blog post](https://orgmode-exocortex.com/2020/05/13/linking-to-zotero-items-and-collections-from-org-mode/) describes some context that might be useful
